// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	danmuauth "github.com/tymon42/live-stream-commont-auth/bili-danmu-auth/api/internal/handler/danmuauth"
	"github.com/tymon42/live-stream-commont-auth/bili-danmu-auth/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/apply",
				Handler: danmuauth.DanmuAuthAplyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/submit",
				Handler: danmuauth.DanmuAuthSubmitHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/status",
				Handler: danmuauth.DanmuAuthStatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/danmuauth/v1"),
	)
}
